import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header'
import StoreProvider from './StoreProvider'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={`${inter.className} px-[42px] py-[53px]`}>
          <Header />
          <main>{children}</main>
        </body>
      </html>
    </StoreProvider>
  )
}
